config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show, :new, :create]
  resources :bands do
    resources :albums 
  end
  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/session/new')
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  live       :boolean          default(TRUE), not null
#  band_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :band, :title, :year, presence: true
  validates :live, inclusion: { in: [true, false] }
  validates :title, uniqueness: { scope: :band_id }
  validates :year, numericality: { minimum: 1900, maximum: 9000 }

  belongs_to :band,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Band
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  primary_key: :id,
  foreign_key: :band_id,
  class_name: :Album

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_session_token

  attr_reader :password #need this attr_reader to access the password parameter when mass-assigning

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    user && user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end





end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Albums.all
    render :index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :current_user_id, :logged_in?

   def current_user
     return nil unless session[:session_token]
     @current_user ||= User.find_by_session_token(session[:session_token])
   end

   def current_user_id
     current_user ? current_user.id : nil
   end

   def logged_in?
     !!current_user
   end

   def login_user!(user)
     session[:session_token] = user.reset_session_token!
   end

   def require_user!
     redirect_to new_session_url if current_user.nil?
   end

   def logout_user!(user)
     user.reset_session_token!
     session[:session_token] = nil
   end
 end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = ['Must specify a band name']
      redirect_to new_band_url
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    @band.update(band_params)
    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = ['Please specify a band']
      render :edit
    end

  end

  def destroy
    @band = Band.find(params[:id])
    @band.delete
    redirect_to bands_url
  end



  private

  def band_params
    params.require(:band).permit(:name)
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login_user!(@user)
      redirect_to user_url(current_user_id)
    else
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    end
  end

  def destroy
    logout_user!(current_user)
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_url
    else
      flash[:errors] = ['Input a valid username and password']
      render :new
    end

  end


  private
  def user_params
    params.require(:user).permit(:email, :password, :session_token)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    
  end

end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/edit.html.erb
<h2> Edit Band Name: </h2>
<br>
<form action="<%=band_url%>" method="post">
<input type="hidden" name="_method" value="patch">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
<label for=""></label>
<input type="text" name="band[name]" value="<%=@band.name%>">

<input type="submit" value="submit">
</form>

app/views/bands/index.html.erb
<a href="<%=new_band_url%>">Create Band</a>
<br>
<h2> All Bands: </h2>
<% @bands.sort_by {|band| band.name}.each do |band| %>
<ul>
  <li>
    <% if current_user %>
    <a class='band_name' href="<%=band_url(band)%>"><%=band.name%></a>
    <% end %></li>
</ul>
  <% end %>

app/views/bands/new.html.erb
<h2> Input Band Name: </h2>
<br>

<%=flash[:errors] %>

<form action="<%=bands_url%>" method="post">
<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
<label for=""></label>
<input type="text" name="band[name]" value="<%=@band.name%>">

<input type="submit" value="submit">
</form>

app/views/bands/show.html.erb
<a href="<%=bands_url%>">All Bands</a>
<div class='show_band'>
<h2> <%=@band.name%> </h2>
<a href="<%=edit_band_url%>">Edit</a>
<form action="<%=band_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="delete">
</form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

<div class = 'container' >
  <h1>Music App</h1>

    <%unless current_user%>
    <a class = 'sign_in' href="<%=new_session_url%>">Sign In</a>


    <a class = 'create_user' href="<%=new_user_url%>">Create User</a>
    <%else%>
    <form action="<%=session_url%>" method="post">
      <input type="hidden" name="authenticity_token" value="form_authenticity_token">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Log Out">
    </form>
    <%end%>
  </div>

  <% if flash[:errors] %>
    <ul>
      <% flash[:errors].each do |error| %>
      <li><%=error%></li>
      <% end %>
    </ul>
    <%end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<form action="<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  <label for="email">Email</label>
  <input id= 'email' type="text" name="user[email]">

  <label for="password">Password</label>
  <input id= 'password' type="password" name="user[password]"%>

  <input type="submit" value="Create User">
</form>

app/views/users/show.html.erb
<h1> User Profile </h1>

<h3> Info </h3>

<p>
<ul>
  <li><%= current_user.email %></li>
</ul>
</p>